version: '2'
services:
  gitlab-runner:
    # Using this  version because the official gitlab/gitlab-runner doesn't support armv7
    image: alpinelinux/gitlab-runner:latest-armv7
    container_name: gitlab-runner
    cpuset: 0-3
    restart: always
    # The container has a makeshift script for entrypoint, agh
    entrypoint: gitlab-runner
    command:
      - run
      - --user=gitlab-runner
      - --working-directory=/var/lib/gitlab-runner
    volumes:
      - gitlab-runner-cache:/cache
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab-runner-cache:

  gitlab-runner-config:
    external: true